name: probible
description: An offline bible app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  google_mobile_ads: ^1.3.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  screen_brightness: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icons_launcher: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    # Image assets
    - assets/images/

    # Bible Versions
    - backend/asv.json
    - backend/bbe.json
    - backend/kjv.json
    - backend/web.json
    - backend/ylt.json

flutter_icons:
  image_path: "assets/images/icon.jpg"
  android: true
  ios: true
  macos: true
  windows: true
  linux: true
  web: true
